- CHANGELOG.md
- package-lock.json
- package.json
Thank you so much cc: @karenychen @qpetraroia ☕️🙏
> Release 0.0.2

- .github/workflows/build.yml
This PR adds the build Action pipeline for this extension. Mid-term goal will be to also add extension publishing from this as well.
How do you guys feel about it. Thanks.
Idea is to also make this part of the PR check as well.
Thank you so much all 🚀 ❤️ 🙏 cc: @karenychen , @sabbour and @qpetraroia cc: and fyi @gambtho
> Add build workflow.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This PR adds concise and well guided issue templates for bugs and feature request. The information will help devs for information which will help in either replicating an issue or improve or add a featue. thanks heaps.
> Add templates for bugs and features.

- .github/workflows/publish.yml
This workflow is for publishing the extension to market place and strictly should be used for build and realise purposes.
This will enable a key attribute of releasing all from one repo and no external dependencies, we need to make sure we adhere to good practices for the release process.
Thank you so much in advance fore review 🙏☕️ cc: @karenychen, @qpetraroia fyi: @gambtho
> Add build and publish pipeline workflow.

- .github/pull_request_template.md
Add Pull request template for folks as a recommendation. cc: ☕️💡 @karenychen, @qpetraroia , @gambtho and @bfoley13
> Add the Pull Request Template.

- resources/webviews/rundrafttool/draft_create.html
- resources/webviews/rundrafttool/draft_generate_workflow.html
- resources/webviews/rundrafttool/draft_setup_gh.html
- resources/webviews/rundrafttool/draft_update.html
Changing the placeholder text in for the draft commands in the devX  extension based on a conversation Ahmed and I had.
This just changes the placeholder text and shouldn't require any major tests.
> change placeholder text

- src/commands/runDraftTool/runDraftSetupGH.ts
> fix fn name

- package.json
- src/commands/runDraftTool/runDraftUpdate.ts
This PR conversations the `draft web app routing annotation` to `multistep wizard` 
This will help in POC for this. thanks. ❤️🙏☕️
Checking in for the effort for making it ready for sample reasons in kubecon.
> multi step web annotation wizard.

- package-lock.json
- src/commands/runDraftTool/helper/runDraftHelper.ts
- src/commands/runDraftTool/runDraftDockerfile.ts
- src/commands/runDraftTool/runDraftGenerateWorkflow.ts
- src/commands/runDraftTool/runDraftSetupGH.ts
- src/commands/runDraftTool/runDraftUpdate.ts
Rename several functions to reflect that the latest binary of draft is no longer always pulled and instead a pinned version is retrieved from package.json
> rename binary functions for clarity

- package-lock.json
- package.json
- src/extension.ts
- src/utils/az.ts
- src/utils/azAccount.d.ts
> add az integration

- package.json
- src/commands/runDraftTool/helper/draftCommandBuilder.ts
- src/commands/runDraftTool/runDraftDockerfile.ts
Add version support in a quickpick
> version support for create dockerfile

- src/commands/runDraftTool/runDraftDockerfile.ts
> fix missing (

- src/commands/runDraftTool/helper/runDraftHelper.ts
> add exe for windows

- package.json
- src/commands/runDraftTool/helper/draftCommandBuilder.ts
- src/commands/runDraftTool/runDraftUpdate.ts
These are ingress UI changes for the extension, this PR depends on this [draft PR ](https://github.com/Azure/draft/pull/145)
> Changes for new ingress ui

- package.json
- src/commands/runDraftTool/runDraftDeployment.ts
- src/commands/runDraftTool/runDraftDockerfile.ts
- src/commands/runDraftTool/runDraftSetupGH.ts
- src/extension.ts
- src/utils/validation.ts
> Add kubernetes deployments and services

- package-lock.json
- package.json
- src/commands/runDraftTool/runDraftDeployment.ts
- src/commands/runDraftTool/runDraftSetupGH.ts
- src/utils/az.ts
> Add ACR fetch

- src/commands/runDraftTool/model/multiStep.ts
- src/commands/runDraftTool/runDraftDeployment.ts
- src/commands/runDraftTool/runDraftDockerfile.ts
- src/extension.ts
- src/utils/az.ts
> add waiter

- package.json
- src/commands/runDraftTool/runBuildContainer.ts
- src/extension.ts
> added wrapper around build container

- package.json
- src/commands/runDraftTool/runDraftDockerfile.ts
- src/extension.ts
> Add link between dockerfile and acr push steps

- src/commands/runDraftTool/runBuildContainer.ts
> add link between build container and draft k8s

- src/commands/runDraftTool/runCreateWorkflow.ts
- src/extension.ts
- src/utils/az.ts
…elected subscriptions
Now using subscriptions selected by az account extension and retrieving all resource groups belonging to those subscriptions
> Using Selected Subscriptions

- src/commands/runDraftTool/runCreateWorkflow.ts
- src/utils/az.ts
Added functionality to get subscriptions to get resource groups if none are provided and re introduced login for getting subscriptions
> Added Default Subscriptions List to Get Resources

- src/commands/runDraftTool/runDraftDeployment.ts
> Full draft dockerfile experience

- src/commands/runDraftTool/runCreateWorkflow.ts
- src/utils/az.ts
Added azure integration for generate ci/cd workflows command
> Added azure integration and removed duplicate function

- src/commands/runDraftTool/runDraftDeployment.ts
- src/commands/runDraftTool/runDraftSetupGH.ts
> refactor setup gh

- package.json
- src/commands/runDraftTool/helper/draftCommandBuilder.ts
- src/commands/runDraftTool/runDraftDeployment.ts
Bump draft version to v0.0.25 which adds the ability to specify a namespace and full image name in the deployments generation.
Add namespace and full image name to createconfig and implement them in the create Deployment flow
> Deployments image name and namespace

- src/commands/runDraftTool/runCreateWorkflow.ts
- src/utils/az.ts
- src/utils/workflowTemplates.ts
Added set context functionality if user isn't admin to prevent user errors like https://github.com/Azure/k8s-deploy/issues/239
> Added set context functionality if user isn't admin

- src/commands/runDraftTool/runDraftDeployment.ts
- src/commands/runDraftTool/runDraftSetupGH.ts
> Autofill defaults

- package-lock.json
- package.json
- src/commands/runDraftTool/runDraftDeployment.ts
- src/utils/k8Helper.ts
This PR is to introduce a new function for interaction with K8's cluster to list namespeaces, services etc..
> K8s wrapper

- src/commands/runDraftTool/runDraftDeployment.ts
- src/utils/k8Helper.ts
> Add create namespace option

- src/commands/runDraftTool/runDraftDockerfile.ts
Update the mappings for the label for selecting the csharp language so that the display label is "c#" and the internal mapped value is "csharp" so draft can parse it correctly.
Also add a warning for languages that don't have any mapped versions to catch a similar error in the future.
> fix csharp label to language mapping

- package-lock.json
- package.json
- src/commands/runDraftTool/runDraftUpdate.ts
- src/extension.ts
- src/utils/az.ts
> Spit out an ingress on the ingress command

- .gitignore
- README.md
- package.json
- src/commands/runDraftTool/runDraftUpdate.ts
- src/utils/az.ts
Added build instructions and fixed a bug that was causing failure to load the resource groups when presented with an authentication token from a different tenant.
> Functionality update for demo

- src/commands/runDraftTool/runDraftUpdate.ts
> Fixed a bug in ingress generation

- src/commands/runDraftTool/runDraftDeployment.ts
- Update the acr generated link to use the azure.cr.io url
- default image tag to `latest` when no tag is provided on the context
- change port prompt to `80` to match the default value
- strip invalid characters and lowercase basename to produce valid default `app name`
> fix acr url and improve appname and image tag defaults

- package-lock.json
- package.json
- src/test/suite/utils/state.test.ts
- src/utils/state.ts
Adds a state wrapper that handles setting and getting extension state. This isn't used anywhere yet but will be used in future additions. 
-  [x] New feature (non-breaking change which adds functionality)
Added unit tests that ensure functionality.
-  [x] My code follows the style guidelines of this project
-  [x] I have performed a self-review of my code
-  [x] I have commented my code, particularly in hard-to-understand areas
-  [x] I have made corresponding changes to the documentation
-  [x] My changes generate no new warnings
-  [x] I have added tests that prove my fix is effective or that my feature works
-  [x] New and existing unit tests pass locally with my changes
-  [x] Any dependent changes have been merged and published in downstream modules
> Add state wrapper

- package.json
- resources/attach-acr.md
- resources/create-acr.md
- resources/create-cluster.md
- resources/get-kubeconfig.md
- resources/login-to-azure.md
- src/commands/runDraftTool/runBuildOnAcr.ts
- src/commands/runDraftTool/runDeploy.ts
- src/commands/runDraftTool/runDraftDeployment.ts
- src/extension.ts
- src/test/suite/utils/kubernetes.test.ts
- src/utils/kubernetes.ts
- src/utils/state.ts
Adds the deploy feature and a prerequisites command.
-  [x] New feature (non-breaking change which adds functionality)
Tested locally. Unit tested where possible. This will be bug bashed before release.
-  [x] My code follows the style guidelines of this project
-  [x] I have performed a self-review of my code
-  [x] I have commented my code, particularly in hard-to-understand areas
-  [x] I have made corresponding changes to the documentation
-  [x] My changes generate no new warnings
-  [x] I have added tests that prove my fix is effective or that my feature works
-  [x] New and existing unit tests pass locally with my changes
-  [x] Any dependent changes have been merged and published in downstream modules
> Add deploy feature

- package.json
- resources/login-to-azure.md
- src/commands/runDraftTool/runDraftDeployment.ts
- src/utils/sort.ts
- Sorts lists
- Improves walkthrough
- Filters out invalid characters for the application name guess
-  [x] New feature (non-breaking change which adds functionality)
-  [x] My code follows the style guidelines of this project
-  [x] I have performed a self-review of my code
-  [x] I have commented my code, particularly in hard-to-understand areas
-  [x ] I have made corresponding changes to the documentation
-  [x] My changes generate no new warnings
-  [x] I have added tests that prove my fix is effective or that my feature works
-  [x] New and existing unit tests pass locally with my changes
-  [x] Any dependent changes have been merged and published in downstream modules
> Small improvements to walkthrough and defaults

- CHANGELOG.md
- package-lock.json
- package.json
> Release v0.1.1

- package-lock.json
- package.json
- resources/login.md
- src/commands/runDraftTool/helper/commonPrompts.ts
- src/commands/runDraftTool/helper/draftCommandBuilder.ts
- src/commands/runDraftTool/model/guidedExperience.ts
- src/commands/runDraftTool/runDeploy.ts
- src/commands/runDraftTool/runDraftDeployment.ts
- src/commands/runDraftTool/runDraftIngress.ts
- src/extension.ts
- src/test/suite/utils/az.test.ts
- src/utils/az.ts
- src/utils/quickPick.ts
- Adds the Draft a web app routing ingress experience
- Slightly modifies the walkthrough to fully walk through user to getting application onto AKS
- Modify our Azure auth method to use the cli :( (auth is just broken for the Azure extension https://github.com/Azure/azure-sdk-for-js/issues/22904)
-  [x] Bug fix (non-breaking change which fixes an issue)
-  [x] This change requires a documentation update
Unit tested where possible. Tested locally for everything else. Will get pms to fully test before releasing but this is already such a huge update it makes sense to get it merged in than make incremental improvements.
I do want to improve the deploy experience to link to the generated ingress address but this pr is already huge. 
-  [x] My code follows the style guidelines of this project …
> add web app routing experience
